// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8xwa0V13y8Za1UobMPSvFCTpBkteYXXM',
    appId: '1:798855635324:web:37f387229d4198e2b744f9',
    messagingSenderId: '798855635324',
    projectId: 'wecare360-69714',
    authDomain: 'wecare360-69714.firebaseapp.com',
    storageBucket: 'wecare360-69714.firebasestorage.app',
    measurementId: 'G-TK2J2PYBZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSDEQ6j0BWVNADaHfvCW3EKJDjmZtjOc',
    appId: '1:798855635324:android:235644a5da2d746bb744f9',
    messagingSenderId: '798855635324',
    projectId: 'wecare360-69714',
    storageBucket: 'wecare360-69714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFk_IBiueqaM4O46gKoifTBBLwLigWwhs',
    appId: '1:798855635324:ios:6d7510578c8303e6b744f9',
    messagingSenderId: '798855635324',
    projectId: 'wecare360-69714',
    storageBucket: 'wecare360-69714.firebasestorage.app',
    iosBundleId: 'com.wecare.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFk_IBiueqaM4O46gKoifTBBLwLigWwhs',
    appId: '1:798855635324:ios:6d7510578c8303e6b744f9',
    messagingSenderId: '798855635324',
    projectId: 'wecare360-69714',
    storageBucket: 'wecare360-69714.firebasestorage.app',
    iosBundleId: 'com.wecare.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8xwa0V13y8Za1UobMPSvFCTpBkteYXXM',
    appId: '1:798855635324:web:dd6a7fd0e6e12486b744f9',
    messagingSenderId: '798855635324',
    projectId: 'wecare360-69714',
    authDomain: 'wecare360-69714.firebaseapp.com',
    storageBucket: 'wecare360-69714.firebasestorage.app',
    measurementId: 'G-PX78TBX7KP',
  );
}
