// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNLLhm3sOmWd_4_ZsUrNWo4In60uCvB_A',
    appId: '1:813675667597:web:56e0875064deb831b882c4',
    messagingSenderId: '813675667597',
    projectId: 'healthcare-hms',
    authDomain: 'healthcare-hms.firebaseapp.com',
    storageBucket: 'healthcare-hms.firebasestorage.app',
    measurementId: 'G-TTBR68P1MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxcaVLmsuu4BDbUExXAlilF9ejDUB7dY',
    appId: '1:813675667597:android:95ac3df6204a5324b882c4',
    messagingSenderId: '813675667597',
    projectId: 'healthcare-hms',
    storageBucket: 'healthcare-hms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRek386SQYyb573QWvPKFVrG2S4GSATz0',
    appId: '1:813675667597:ios:0941f93406813119b882c4',
    messagingSenderId: '813675667597',
    projectId: 'healthcare-hms',
    storageBucket: 'healthcare-hms.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRek386SQYyb573QWvPKFVrG2S4GSATz0',
    appId: '1:813675667597:ios:0941f93406813119b882c4',
    messagingSenderId: '813675667597',
    projectId: 'healthcare-hms',
    storageBucket: 'healthcare-hms.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNLLhm3sOmWd_4_ZsUrNWo4In60uCvB_A',
    appId: '1:813675667597:web:cd4312aa989bc811b882c4',
    messagingSenderId: '813675667597',
    projectId: 'healthcare-hms',
    authDomain: 'healthcare-hms.firebaseapp.com',
    storageBucket: 'healthcare-hms.firebasestorage.app',
    measurementId: 'G-K575ZTXKR1',
  );

}